# Generated by Django 5.0.14 on 2026-01-22 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(help_text='Day of month, e.g., "15"', max_length=10)),
                ('day', models.CharField(help_text='Day name, e.g., "Sun"', max_length=10)),
                ('month', models.CharField(help_text='Month abbrev, e.g., "FEB"', max_length=10)),
                ('time', models.CharField(help_text='Event time, e.g., "11:00 AM"', max_length=20)),
                ('event_date', models.DateField(help_text='Actual date for sorting and filtering')),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum ticket price for this event', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('WTA', 'WTA 1000'), ('ATP', 'ATP 500')], max_length=3)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(default='Dubai Duty Free Tennis Stadium', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['type', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(default='#1e824c', help_text='Hex color code for UI display', max_length=20)),
                ('seats_total', models.PositiveIntegerField(default=100)),
                ('seats_available', models.PositiveIntegerField(default=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='events.event')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.tournament'),
        ),
    ]
