# Generated by Django 5.0.14 on 2026-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_frontend',
            field=models.BooleanField(default=True, help_text='False = Legacy category, hidden from UI entirely (keeps order history)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = SOLD OUT (visible but not purchasable)'),
        ),
    ]
