# Generated by Django 5.0.14 on 2026-01-29 17:44
# Modified to include data migration for existing records

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slug(model, base_slug, existing_slugs):
    """Generate a unique slug, checking against existing_slugs set."""
    slug = base_slug
    counter = 2

    while slug in existing_slugs:
        slug = f"{base_slug}-{counter}"
        counter += 1

    existing_slugs.add(slug)
    return slug


def backfill_tournament_slugs(apps, schema_editor):
    """Backfill slugs for existing Tournament records."""
    Tournament = apps.get_model('events', 'Tournament')
    existing_slugs = set()

    for tournament in Tournament.objects.all():
        if not tournament.slug:
            base_slug = slugify(f"{tournament.name}-{tournament.year}")
            tournament.slug = generate_unique_slug(Tournament, base_slug, existing_slugs)
            tournament.save(update_fields=['slug'])


def backfill_event_slugs(apps, schema_editor):
    """Backfill slugs for existing Event records."""
    Event = apps.get_model('events', 'Event')
    existing_slugs = set()

    for event in Event.objects.all():
        if not event.slug:
            base_slug = slugify(f"{event.title}-{event.month}-{event.date}")
            event.slug = generate_unique_slug(Event, base_slug, existing_slugs)
            event.save(update_fields=['slug'])


def reverse_backfill(apps, schema_editor):
    """Reverse operation - clear slugs (for rollback)."""
    pass  # No action needed, field will be removed


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_show_on_frontend_to_category'),
    ]

    operations = [
        # Step 1: Add slug field to Tournament WITHOUT unique constraint
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(
                blank=True,
                default='',
                help_text='SEO-friendly URL slug. Auto-generated on first save.',
                max_length=255,
            ),
            preserve_default=False,
        ),

        # Step 2: Backfill Tournament slugs
        migrations.RunPython(backfill_tournament_slugs, reverse_backfill),

        # Step 3: Add unique constraint to Tournament slug
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='SEO-friendly URL slug. Auto-generated on first save.',
                max_length=255,
                unique=True,
            ),
        ),

        # Step 4: Add slug field to Event WITHOUT unique constraint
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(
                blank=True,
                default='',
                help_text='SEO-friendly URL slug. Auto-generated on first save.',
                max_length=255,
            ),
            preserve_default=False,
        ),

        # Step 5: Backfill Event slugs
        migrations.RunPython(backfill_event_slugs, reverse_backfill),

        # Step 6: Add unique constraint to Event slug
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='SEO-friendly URL slug. Auto-generated on first save.',
                max_length=255,
                unique=True,
            ),
        ),
    ]
