# Generated by Django 5.0.14 - Clean squashed migration

import uuid
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='FROZEN: Total amount at time of order creation. Never recalculate from catalog.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID. Used for idempotency checks.', max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='FROZEN: Number of tickets at order time', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='FROZEN: Price per ticket at order time. Never recalculate from catalog.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='FROZEN: unit_price * quantity at order time', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('event_title', models.CharField(help_text='FROZEN: Event title at order time', max_length=200)),
                ('event_date', models.CharField(help_text='FROZEN: Event date at order time', max_length=10)),
                ('event_month', models.CharField(help_text='FROZEN: Event month at order time', max_length=10)),
                ('event_day', models.CharField(help_text='FROZEN: Event day at order time', max_length=10)),
                ('event_time', models.CharField(help_text='FROZEN: Event time at order time', max_length=20)),
                ('category_name', models.CharField(help_text='FROZEN: Category name at order time', max_length=100)),
                ('venue', models.CharField(help_text='FROZEN: Venue at order time', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='events.event')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='events.category')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
    ]
