# Generated by Django 5.0.14 on 2026-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3),
        ),
    ]
