# Generated by Django 5.0.14 on 2026-01-29 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID. Used for idempotency checks.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FROZEN: Total amount at time of order creation. Never recalculate from catalog.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category_name',
            field=models.CharField(help_text='FROZEN: Category name at order time', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='event_date',
            field=models.CharField(help_text='FROZEN: Event date at order time', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='event_day',
            field=models.CharField(help_text='FROZEN: Event day at order time', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='event_month',
            field=models.CharField(help_text='FROZEN: Event month at order time', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='event_time',
            field=models.CharField(help_text='FROZEN: Event time at order time', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='event_title',
            field=models.CharField(help_text='FROZEN: Event title at order time', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='FROZEN: Number of tickets at order time', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='FROZEN: unit_price * quantity at order time', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='FROZEN: Price per ticket at order time. Never recalculate from catalog.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='venue',
            field=models.CharField(help_text='FROZEN: Venue at order time', max_length=200),
        ),
    ]
