# Generated by Django 5.0.14 on 2026-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_sales_channel_and_stripe_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('other', 'Other')], db_index=True, default='stripe', help_text='Payment provider name', max_length=50)),
                ('provider_event_id', models.CharField(db_index=True, help_text='Unique event ID from provider (e.g., Stripe evt_...)', max_length=255)),
                ('event_type', models.CharField(help_text='Event type (e.g., checkout.session.completed)', max_length=100)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='received', help_text='Current processing status', max_length=20)),
                ('raw_payload', models.JSONField(default=dict, help_text='Full webhook payload as JSON')),
                ('related_order_id', models.UUIDField(blank=True, db_index=True, help_text='Related order ID if applicable', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if processing failed')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When webhook was first received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'processing_status'], name='orders_webh_provide_48cff7_idx'), models.Index(fields=['received_at'], name='orders_webh_receive_984d12_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_event'),
        ),
    ]
