# Generated by Django 5.0.14 on 2026-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_webhook_event_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(db_index=True, help_text='Order ID this notification relates to')),
                ('notification_type', models.CharField(choices=[('order_paid', 'Order Paid'), ('order_created', 'Order Created'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded')], db_index=True, help_text='Type of notification to send', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current delivery status', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts')),
                ('last_error', models.TextField(blank=True, default='', help_text='Last error message if delivery failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was queued')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was successfully sent', null=True)),
            ],
            options={
                'verbose_name': 'Notification Outbox',
                'verbose_name_plural': 'Notification Outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_noti_status_f39fac_idx'), models.Index(fields=['order_id', 'notification_type'], name='orders_noti_order_i_9159b1_idx')],
            },
        ),
    ]
