# Generated by Django 5.0.14 on 2026-02-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_notification_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('other', 'Other')], db_index=True, default='stripe', help_text='Payment provider (stripe, paypal, etc.)', max_length=50)),
                ('provider_event_id', models.CharField(db_index=True, help_text='Unique event ID from provider (e.g., Stripe evt_...)', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Event type (e.g., checkout.session.completed)', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount (in currency units, not cents)', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', help_text='ISO 4217 currency code', max_length=3)),
                ('raw_payload', models.JSONField(default=dict, help_text='Full webhook payload as received from provider')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('error', 'Error')], db_index=True, default='received', help_text='Processing status', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='', help_text='Reason for status (e.g., error message or ignore reason)')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When event was received from provider')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Associated order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Log',
                'verbose_name_plural': 'Payment Logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='orders_paym_provide_ae84f9_idx'), models.Index(fields=['received_at'], name='orders_paym_receive_5ef12b_idx'), models.Index(fields=['order', 'received_at'], name='orders_paym_order_i_ea160e_idx')],
            },
        ),
    ]
