# Generated by Django 5.0.14 on 2026-02-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_payment_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(db_index=True, help_text='Status before the change', max_length=20)),
                ('to_status', models.CharField(db_index=True, help_text='Status after the change', max_length=20)),
                ('source', models.CharField(choices=[('api', 'API'), ('webhook', 'Webhook'), ('admin', 'Admin'), ('system', 'System')], db_index=True, help_text='What triggered the status change', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Optional note (e.g., reason for cancellation, payment_intent_id)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the status change occurred')),
                ('order', models.ForeignKey(help_text='Order whose status changed', on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order State Log',
                'verbose_name_plural': 'Order State Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_ab77bc_idx'), models.Index(fields=['from_status', 'to_status'], name='orders_orde_from_st_551f07_idx')],
            },
        ),
    ]
