# Generated by Django 5.0.14 on 2026-02-06 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_order_state_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique site code (immutable after creation). Example: "dubaitennistickets"', max_length=50, unique=True)),
                ('domain', models.CharField(help_text='Site domain. Example: "dubaitennistickets.com"', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', help_text='active=accepts orders, disabled=blocks new orders', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site that originated this order (FROZEN after creation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.site'),
        ),
    ]
